/.
/sw
/sw/lib
/sw/lib/python3.6
/sw/lib/python3.6/site-packages
/sw/lib/python3.6/site-packages/beautifulsoup4-4.6.0-py3.6.egg-info
/sw/lib/python3.6/site-packages/beautifulsoup4-4.6.0-py3.6.egg-info/PKG-INFO
/sw/lib/python3.6/site-packages/beautifulsoup4-4.6.0-py3.6.egg-info/SOURCES.txt
/sw/lib/python3.6/site-packages/beautifulsoup4-4.6.0-py3.6.egg-info/dependency_links.txt
/sw/lib/python3.6/site-packages/beautifulsoup4-4.6.0-py3.6.egg-info/requires.txt
/sw/lib/python3.6/site-packages/beautifulsoup4-4.6.0-py3.6.egg-info/top_level.txt
/sw/lib/python3.6/site-packages/bs4
/sw/lib/python3.6/site-packages/bs4/__init__.py
/sw/lib/python3.6/site-packages/bs4/__pycache__
/sw/lib/python3.6/site-packages/bs4/__pycache__/__init__.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/__pycache__/dammit.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/__pycache__/diagnose.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/__pycache__/element.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/__pycache__/testing.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/builder
/sw/lib/python3.6/site-packages/bs4/builder/__init__.py
/sw/lib/python3.6/site-packages/bs4/builder/__pycache__
/sw/lib/python3.6/site-packages/bs4/builder/__pycache__/__init__.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/builder/__pycache__/_html5lib.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/builder/__pycache__/_htmlparser.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/builder/__pycache__/_lxml.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/builder/_html5lib.py
/sw/lib/python3.6/site-packages/bs4/builder/_htmlparser.py
/sw/lib/python3.6/site-packages/bs4/builder/_lxml.py
/sw/lib/python3.6/site-packages/bs4/dammit.py
/sw/lib/python3.6/site-packages/bs4/diagnose.py
/sw/lib/python3.6/site-packages/bs4/element.py
/sw/lib/python3.6/site-packages/bs4/testing.py
/sw/lib/python3.6/site-packages/bs4/tests
/sw/lib/python3.6/site-packages/bs4/tests/__init__.py
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/__init__.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_builder_registry.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_docs.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_html5lib.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_htmlparser.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_lxml.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_soup.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/__pycache__/test_tree.cpython-36.pyc
/sw/lib/python3.6/site-packages/bs4/tests/test_builder_registry.py
/sw/lib/python3.6/site-packages/bs4/tests/test_docs.py
/sw/lib/python3.6/site-packages/bs4/tests/test_html5lib.py
/sw/lib/python3.6/site-packages/bs4/tests/test_htmlparser.py
/sw/lib/python3.6/site-packages/bs4/tests/test_lxml.py
/sw/lib/python3.6/site-packages/bs4/tests/test_soup.py
/sw/lib/python3.6/site-packages/bs4/tests/test_tree.py
/sw/share
/sw/share/doc
/sw/share/doc/beautifulsoup-py36
/sw/share/doc/beautifulsoup-py36/PKG-INFO

