/.
/sw
/sw/lib
/sw/lib/python2.7
/sw/lib/python2.7/site-packages
/sw/lib/python2.7/site-packages/beautifulsoup4-4.6.0-py2.7.egg-info
/sw/lib/python2.7/site-packages/beautifulsoup4-4.6.0-py2.7.egg-info/PKG-INFO
/sw/lib/python2.7/site-packages/beautifulsoup4-4.6.0-py2.7.egg-info/SOURCES.txt
/sw/lib/python2.7/site-packages/beautifulsoup4-4.6.0-py2.7.egg-info/dependency_links.txt
/sw/lib/python2.7/site-packages/beautifulsoup4-4.6.0-py2.7.egg-info/requires.txt
/sw/lib/python2.7/site-packages/beautifulsoup4-4.6.0-py2.7.egg-info/top_level.txt
/sw/lib/python2.7/site-packages/bs4
/sw/lib/python2.7/site-packages/bs4/__init__.py
/sw/lib/python2.7/site-packages/bs4/__init__.pyc
/sw/lib/python2.7/site-packages/bs4/builder
/sw/lib/python2.7/site-packages/bs4/builder/__init__.py
/sw/lib/python2.7/site-packages/bs4/builder/__init__.pyc
/sw/lib/python2.7/site-packages/bs4/builder/_html5lib.py
/sw/lib/python2.7/site-packages/bs4/builder/_html5lib.pyc
/sw/lib/python2.7/site-packages/bs4/builder/_htmlparser.py
/sw/lib/python2.7/site-packages/bs4/builder/_htmlparser.pyc
/sw/lib/python2.7/site-packages/bs4/builder/_lxml.py
/sw/lib/python2.7/site-packages/bs4/builder/_lxml.pyc
/sw/lib/python2.7/site-packages/bs4/dammit.py
/sw/lib/python2.7/site-packages/bs4/dammit.pyc
/sw/lib/python2.7/site-packages/bs4/diagnose.py
/sw/lib/python2.7/site-packages/bs4/diagnose.pyc
/sw/lib/python2.7/site-packages/bs4/element.py
/sw/lib/python2.7/site-packages/bs4/element.pyc
/sw/lib/python2.7/site-packages/bs4/testing.py
/sw/lib/python2.7/site-packages/bs4/testing.pyc
/sw/lib/python2.7/site-packages/bs4/tests
/sw/lib/python2.7/site-packages/bs4/tests/__init__.py
/sw/lib/python2.7/site-packages/bs4/tests/__init__.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_builder_registry.py
/sw/lib/python2.7/site-packages/bs4/tests/test_builder_registry.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_docs.py
/sw/lib/python2.7/site-packages/bs4/tests/test_docs.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_html5lib.py
/sw/lib/python2.7/site-packages/bs4/tests/test_html5lib.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_htmlparser.py
/sw/lib/python2.7/site-packages/bs4/tests/test_htmlparser.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_lxml.py
/sw/lib/python2.7/site-packages/bs4/tests/test_lxml.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_soup.py
/sw/lib/python2.7/site-packages/bs4/tests/test_soup.pyc
/sw/lib/python2.7/site-packages/bs4/tests/test_tree.py
/sw/lib/python2.7/site-packages/bs4/tests/test_tree.pyc
/sw/share
/sw/share/doc
/sw/share/doc/beautifulsoup-py27
/sw/share/doc/beautifulsoup-py27/PKG-INFO

